apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cva737wvj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cva737wvj-nodejs 
  name: cva737wvj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: cva737wvj-nodejs 
